export const GET_PROJECTS_LIST ='GET_PROJECT_LIST'
export const GET_PROJECT_INFO ='GET_PROJECT_INFO'
export const ADD_PROJECT ='ADD_PROJECT'
export const REMOVE_PROJECT = 'REMOVE_PROJECT'
export const UPDATE_PROJECT_INFO= 'UPDATE_PROJECT_INFO'

export const SET_PROJECTS_LIST= 'SET_PROJECT_LIST'
export const SET_PROJECT_INFO='SET_PROJECT_INFO'